import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" className={jetbrains.variable}>
      <head>
        <title>Ngọc Rồng</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/gif"
          href="https://nrowar.online/assets/images/char/rose.png"
        />
      </head>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
