// app/layout.tsx
import "./globals.css";
import { JetBrains_Mono } from "next/font/google";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
  display: "swap",
});

export const metadata = {
  title: "Ngọc Rồng",
  description: "Generated by create next app",
  icons: {
    icon: "https://nrowar.online/assets/images/char/rose.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi" className={jetbrains.variable}>
      <body>{children}</body>
    </html>
  );
}
