"use client";

import React, { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import {
  Layout,
  Menu,
  Typography,
  Space,
  Divider,
  ConfigProvider,
  theme,
  Button,
} from "antd";
import {
  HomeOutlined,
  UserOutlined,
  ShoppingCartOutlined,
  GiftOutlined,
  BoxPlotOutlined,
  InfoCircleOutlined,
  AppstoreOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
} from "@ant-design/icons";
import type { MenuProps } from "antd";

const { Sider, Content } = Layout;
const { Title, Text } = Typography;

// Menu items với Ant Design icons
const menuItems: MenuProps["items"] = [
  {
    key: "/",
    icon: <HomeOutlined />,
    label: <Link href="/">Trang chủ</Link>,
  },
  {
    key: "/admin/user",
    icon: <UserOutlined />,
    label: <Link href="/admin/user">Quản lý User</Link>,
  },
  {
    key: "/admin/giftcodes",
    icon: <GiftOutlined />,
    label: <Link href="/admin/giftcodes">Quản lý Giftcodes</Link>,
  },
  {
    key: "/manage-shop",
    icon: <ShoppingCartOutlined />,
    label: <Link href="/admin/manage-shop">Quản lý shop</Link>,
  },
  {
    key: "/manage-item",
    icon: <BoxPlotOutlined />,
    label: <Link href="/admin/manage-item">Quản lý item</Link>,
  },
  {
    key: "/about",
    icon: <InfoCircleOutlined />,
    label: <Link href="/about">Giới thiệu</Link>,
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [collapsed, setCollapsed] = useState(false);
  const pathname = usePathname();

  return (
    <html lang="vi">
      <head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        style={{ margin: 0, padding: 0, height: "100vh", overflow: "hidden" }}
      >
        <ConfigProvider
          theme={{
            algorithm: theme.defaultAlgorithm,
            token: {
              colorPrimary: "#F25C05",
              colorBgContainer: "#FFF8E7",
              colorBgLayout: "#FDE5C1",
              borderRadius: 8,
            },
          }}
        >
          <Layout style={{ height: "100vh" }}>
            {/* Sidebar */}
            <Sider
              collapsible
              collapsed={collapsed}
              onCollapse={setCollapsed}
              trigger={null}
              width={280}
              style={{
                background: "linear-gradient(180deg, #FDE5C1 0%, #FCD5A5 100%)",
                boxShadow: "2px 0 8px rgba(0,0,0,0.1)",
                borderRight: "1px solid #CC4E04",
              }}
            >
              {/* Header Logo */}
              <div
                style={{
                  padding: "24px 16px",
                  textAlign: collapsed ? "center" : "left",
                  borderBottom: "1px solid rgba(204, 78, 4, 0.2)",
                }}
              >
                <Space align="center" size="middle">
                  <div
                    style={{
                      padding: "8px",
                      background: "rgba(242, 92, 5, 0.1)",
                      borderRadius: "8px",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    <AppstoreOutlined
                      style={{
                        fontSize: collapsed ? "24px" : "28px",
                        color: "#F25C05",
                      }}
                    />
                  </div>
                  {!collapsed && (
                    <div>
                      <Title
                        level={3}
                        style={{
                          margin: 0,
                          color: "#CC4E04",
                          fontWeight: "bold",
                          textShadow: "0 1px 2px rgba(0,0,0,0.1)",
                        }}
                      >
                        My App
                      </Title>
                      <Text
                        style={{
                          color: "#CC4E04",
                          opacity: 0.8,
                          fontSize: "12px",
                        }}
                      >
                        Admin Dashboard
                      </Text>
                    </div>
                  )}
                </Space>
              </div>

              {/* Collapse Button */}
              <div style={{ padding: "16px", textAlign: "center" }}>
                <Button
                  type="text"
                  icon={
                    collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />
                  }
                  onClick={() => setCollapsed(!collapsed)}
                  style={{
                    fontSize: "16px",
                    width: "100%",
                    height: "40px",
                    color: "#CC4E04",
                    background: "rgba(242, 92, 5, 0.1)",
                    border: "1px solid rgba(242, 92, 5, 0.2)",
                  }}
                />
              </div>

              {/* Navigation Menu */}
              <Menu
                mode="inline"
                selectedKeys={[pathname]}
                items={menuItems}
                style={{
                  background: "transparent",
                  border: "none",
                  padding: "0 16px",
                }}
                theme="light"
                inlineIndent={24}
              />

              {/* Footer */}
              {!collapsed && (
                <div
                  style={{
                    position: "absolute",
                    bottom: "16px",
                    left: "16px",
                    right: "16px",
                  }}
                >
                  <Divider
                    style={{
                      margin: "16px 0",
                      borderColor: "rgba(204, 78, 4, 0.2)",
                    }}
                  />
                  <Text
                    style={{
                      fontSize: "11px",
                      color: "rgba(204, 78, 4, 0.7)",
                      textAlign: "center",
                      display: "block",
                    }}
                  >
                    © 2025 My App
                  </Text>
                  <Text
                    style={{
                      fontSize: "10px",
                      color: "rgba(204, 78, 4, 0.5)",
                      textAlign: "center",
                      display: "block",
                      marginTop: "4px",
                    }}
                  >
                    Version 1.0.0
                  </Text>
                </div>
              )}
            </Sider>

            {/* Main Content */}
            <Layout>
              <Content
                style={{
                  margin: 0,
                  padding: "24px",
                  background: "#FFF8E7",
                  overflow: "auto",
                  height: "100vh",
                  position: "relative",
                }}
              >
                {/* Content Background Pattern */}
                <div
                  style={{
                    position: "absolute",
                    top: 0,
                    left: 0,
                    right: 0,
                    bottom: 0,
                    background: `
                      radial-gradient(circle at 20% 50%, rgba(242, 92, 5, 0.03) 0%, transparent 50%),
                      radial-gradient(circle at 80% 20%, rgba(204, 78, 4, 0.03) 0%, transparent 50%),
                      radial-gradient(circle at 40% 80%, rgba(242, 92, 5, 0.02) 0%, transparent 50%)
                    `,
                    pointerEvents: "none",
                  }}
                />
                <div
                  style={{
                    position: "relative",
                    zIndex: 1,
                    margin: "0 auto",
                    background: "rgba(255, 255, 255, 0.8)",
                    borderRadius: "12px",
                    padding: "24px",
                    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
                    backdropFilter: "blur(10px)",
                    border: "1px solid rgba(224, 193, 135, 0.3)",
                    minHeight: "calc(100vh - 48px)",
                  }}
                >
                  {children}
                </div>
              </Content>
            </Layout>
          </Layout>
        </ConfigProvider>
      </body>
    </html>
  );
}
