// app/data/rewards.ts
import { RewardItem } from "./types";

export const ORIGINAL_REWARDS_DATA: RewardItem[] = [
  {
    id: 1,
    label: "Thỏi vàng",
    value: "Random 1-100 thỏi",
    color: "#4A90E2",
    icon: "http://103.78.0.42/public/icon/4028.png",
    rarity: "Rare",
    revealed: false,
  },
  {
    id: 2,
    label: "Bông Tai Cấp 5",
    value: "x1",
    color: "#F5A623",
    icon: "http://103.78.0.42/public/icon/7993.png",
    rarity: "Common",
    revealed: false,
  },
  {
    id: 3,
    label: "Cải Trang Mega Broly",
    value: "x1",
    color: "#D0021B",
    icon: "http://103.78.0.42/public/icon/17548.png",
    rarity: "Epic",
    revealed: false,
  },
  {
    id: 4,
    label: "Cảm ơn bạn đã tham gia",
    value: "Cảm ơn",
    color: "#7ED321",
    icon: "🎉",
    rarity: "Common",
    revealed: false,
  },
  {
    id: 5,
    label: "Ván bay Mây Mưa",
    value: "x1",
    color: "#50E3C2",
    icon: "http://103.78.0.42/public/icon/18067.png",
    rarity: "Uncommon",
    revealed: false,
  },
  {
    id: 6,
    label: "Cải trang Goku Rose VIP",
    value: "x1",
    color: "#F8E71C",
    icon: "http://103.78.0.42/public/icon/18044.png",
    rarity: "Legendary",
    revealed: false,
  },
  {
    id: 7,
    label: "Đá Quý Huyền Thoại",
    value: "x1",
    color: "#9013FE",
    icon: "🔥",
    rarity: "Mythic",
    revealed: false,
  },
  {
    id: 8,
    label: "Danh Hiệu Trùm Săn Boss",
    value: "x1",
    color: "#FF6B35",
    icon: "http://103.78.0.42/public/icon/18248.png",
    rarity: "Rare",
    revealed: false,
  },
  {
    id: 9,
    label: "Nhận để rút thăm",
    value: "Spin",
    color: "#FFD700",
    icon: "🎯",
    rarity: "Common",
    revealed: false,
  },
];
